### ISSUE TITLE
cannot import name 'rgbww_to_color_temperature' from 'homeassistant.util.color'

### ISSUE THREAD

**Issue by Lukey1979** [bdraco/homekit#2]
Hi mate, any reason why I would be receiving this error after updating HA to 2011.2.1 

LOG:

Logger: homeassistant.config_entries
Source: config_entries.py:735 
First occurred: 11:28:53 AM (19 occurrences) 
Last logged: 11:33:30 AM

Error occurred loading configuration flow for integration homekit: cannot import name 'rgbww_to_color_temperature' from 'homeassistant.util.color' (/usr/src/homeassistant/homeassistant/util/color.py)

**Comment by bdraco** [comment]
Please update to 2021.2.2

**Comment by bdraco** [comment]
This repo is for testing though so its probably better to delete `/config/custom_components/homekit` and revert to the built-in version.

**Comment by Lukey1979** [comment]
Ah yes, Thank you. Updated and error has been fixed :-) Also I kept using this repo as I believed the built-in 'HomeKit' Integration still separated the Lights into 2 (RGB and Temperature) in HomeKit.. Is this not the case anymore?

**Comment by bdraco** [comment]
>  Is this not the case anymore?

No, at least not for a few months
